name: dependency_scope
description: This package was created to facilitate the use of Dependency Injection in a Flutter project
version: 1.0.1
repository: https://github.com/kkkivannn/dependency_scope

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
